import { AssistanceCompany, Technician, ServiceRequest } from './types';

export const MOCK_COMPANIES: AssistanceCompany[] = [
  { id: '1', name: 'IKE Asistencia', accounts: ['Coomeva', 'HDI', 'Banco de Bogotá', 'Sura'] },
  { id: '2', name: 'IGS', accounts: ['Allianz', 'Axa Colpatria', 'Mapfre'] },
  { id: '3', name: 'Mawdy', accounts: ['Davivienda', 'BBVA'] },
  { id: '4', name: 'Assisprex', accounts: ['Generali', 'Liberty Seguros'] },
];

export const MOCK_TECHNICIANS: Technician[] = [
  { id: 't1', name: 'Juan Perez', specialties: ['Plomería', 'Destaponamiento'], activeTasks: 2 },
  { id: 't2', name: 'Carlos Ruiz', specialties: ['Electricidad', 'Instalación'], activeTasks: 1 },
  { id: 't3', name: 'Luis Gomez', specialties: ['Cerrajería'], activeTasks: 0 },
  { id: 't4', name: 'Mario Diaz', specialties: ['Trabajo en Alturas', 'Vidriería'], activeTasks: 3 },
];

export const MOCK_REQUESTS: ServiceRequest[] = [
  {
    id: 'REQ-001',
    category: 'Plomería',
    companyId: '1',
    accountName: 'Coomeva',
    status: 'pending',
    insuredName: 'Ana Maria Restrepo',
    claimNumber: 'EXP-998822',
    address: 'Calle 100 #15-30, Apt 502, Bogotá',
    phoneNumber: '310 555 1234',
    description: 'Fuga de agua en baño principal, goteo constante.',
    notes: 'El cliente reporta que el agua sale por debajo del sanitario.',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'REQ-002',
    category: 'Electricidad',
    companyId: '1',
    accountName: 'HDI',
    status: 'assigned',
    technicianId: 't2',
    insuredName: 'Roberto Gomez',
    claimNumber: 'EXP-774411',
    address: 'Carrera 7 #127-10, Casa 4',
    phoneNumber: '315 222 9876',
    description: 'Cortocircuito en tomas de la cocina.',
    notes: 'Se requiere revisión de breakers principales.',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'REQ-003',
    category: 'Cerrajería',
    companyId: '2',
    accountName: 'Allianz',
    status: 'in_progress',
    technicianId: 't3',
    insuredName: 'Claudia Lopez',
    claimNumber: 'EXP-553300',
    address: 'Avenida Boyacá #53-22',
    phoneNumber: '320 444 5566',
    description: 'Apertura de puerta de emergencia trabada.',
    notes: 'El técnico ya se encuentra en sitio evaluando el cilindro.',
    createdAt: new Date(Date.now() - 10800000).toISOString(),
    updatedAt: new Date(Date.now() - 5400000).toISOString(),
  },
  {
    id: 'REQ-004',
    category: 'Destaponamiento',
    companyId: '3',
    accountName: 'Davivienda',
    status: 'completed',
    technicianId: 't1',
    insuredName: 'Juan Carlos Velez',
    claimNumber: 'EXP-112233',
    address: 'Transversal 23 #94-55',
    phoneNumber: '300 111 2233',
    description: 'Sifón de patio obstruido por sedimentos.',
    notes: 'Se realizó limpieza profunda con sonda eléctrica. Se verificó drenaje correcto.',
    summary: 'Limpieza de sifón de patio completada exitosamente usando sonda eléctrica.',
    report: 'Se atendió solicitud de destaponamiento en área de patio. Se utilizó sonda eléctrica de 1/2 pulgada para remover sedimentos orgánicos. Pruebas de drenaje satisfactorias.',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 82800000).toISOString(),
  }
];
